### ISSUE TITLE
Loops forever when getting latest versions and can't resolve github url

### ISSUE THREAD

**Issue by minusworld** [returntocorp/inputset-generator#4]
<img width="1168" alt="Screen Shot 2019-09-17 at 6 47 04 PM" src="https://user-images.githubusercontent.com/2374948/65097801-a8efbf80-d97b-11e9-9066-12e9dbe7ac34.png">

**Comment by minusworld** [comment]
Makes the assumption that the url will contain the owner name, but that isn't the case for babel packages (all babel packages are weird anyway)

**Comment by bafulton** [comment]
ISG assumes all github packages have urls with the structure "https://api.github.com/repos/[OWNER]/[NAME]", so it looks like it thinks the owner is "packages". Could you walk me through the steps to get to this point? Did you start with the top1kstarred github weblist?

**Comment by minusworld** [comment]
Sure thing! I took a round-about way to generate Git URLs by mining them out of npm packages.  I wanted to get the top npm packages but also point to their GitHub URLs.  It looks like the babel series of packages points to a specific git (not GitHub) URL.  Their URLs are of the form .../tree/master/babel-core/...

Of more importance, I think, than accounting for this case, is just making sure that it fails gracefully when it can't resolve a URL.  I would like to keep downloading the metadata even if that URL can't be resolved.  Some loss is OK by me.  Or maybe we could introduce something like a "strict" flag that forces resolution for the URLs? 🤷‍♂️

**Comment by bafulton** [comment]
As things stand, the github commits request code assumes a bad response is due to a network/request hiccup, and just moves on to requesting the next commit page. How about it assume a 404 is due to a malformed url and move on to the next repo instead?

**Comment by minusworld** [comment]
Perfect!  Thank you! Stamped and merged.
